language: ruby
rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - jruby-19mode
  - rbx
env:
  - POSTGIS=1.5
  - POSTGIS=2.0
gemfile:
  - travis/ar31.gemfile
  - travis/ar32.gemfile
  - travis/ar40.gemfile
  - travis/ar41.gemfile
matrix:
  exclude:
    - rvm: 1.9.3
      gemfile: travis/ar41.gemfile
      env: POSTGIS=1.5
    - rvm: 1.9.3
      gemfile: travis/ar41.gemfile
      env: POSTGIS=2.0
# END TEMP
before_install: ./travis/before_install.sh
before_script: ./travis/before_script.sh
script: bundle exec rake test
